### ISSUE TITLE
Game Timer

### ISSUE THREAD

**Issue by itspebbleboy** [GDACollab/TacoCat#266] opened 2023-05-09 02:41 UTC
Game timer done through the Game Manager, only should start when starting from main menu, should be stopped in pause menus & cutscenes

Given a start time (i.e. 09:00AM) & end time (i.e. 10:00PM) use the float (going from 0 to 1) to convert it into that time (so it can be referenced in tacomaking & the cutscene)

**Comment by HydrangeaColored** [comment] 2023-05-18 00:23
branch: final_StevenTimer
(also includes the in-game clock in console log)
added timer that persists through scenes and pauses when in menu and cutscenes. totalTime is how much time is given to the player for the good ending. timeRemaining and countdownTimer will update itself depending on totalTime. They are set as visible for debugging purposes for the design team. timeRemaining and countdownTimer are both set as sliders to make it easy for the design team to assess it visually. Although sliding countdownTimer will have no effect, they can manipulate it via the timeRemaining timer which will change the countdownTimer in turn. I also added a clock which starts at 8 AM and ends at 8 PM. The speed of the passage of time will change depending on the totalTime given at the start.

**Comment by skysfalling** [comment] 2023-05-19 02:32
Merged to master, works as intended thank you for your hard work! I have a couple notes I was hoping you could address before I move this task to 'Done'.

- Can you pull master into your branch and then update the code so that the start AM time shows in the cutscene? 
- Could you convert the description you commented ^^ into a [Tooltip('')] above the corresponding variables? 
- And finally, could you contain the Timer code into a function named 'GameTimer()' that takes in any parameters you deem necessary, even if its none.

**Comment by HydrangeaColored** [comment] 2023-05-19 03:58
- fixed bug that caused time to not update in the initial cutscene
- added tooltip to all variables
- cleaned up code. I couldn't contain it all in 1 function but I managed to spread it into 3 functions: gameTimerStart, calculateTime, and gameTimerUpdate. I put them all at the bottom together so they're grouped up.
- moved the clock number back to be on the clock asset

(Note: Just as a heads up that I forgot to mention in my last comment, hardCapHour and hardCapMinute isn't exact if the total game time is super short (like ~5 seconds total). It's approximate since 𐤃time in-game changes depending on the total game time and start and end hour. So if you set the end time to be 11:37PM, the timer might stop at 11:35PM instead if the next jump will be over 11:37PM. This shouldn't be an issue in an actual game but I just wanted to point it out so folks know during debugging.)

**Comment by skysfalling** [comment] 2023-05-19 04:04
Awesome, looks and works great! Thank you very much :) Merged to master

**Closed by skysfalling** 2023-05-19 04:04 UTC
Labels: programming
